### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#1]
![Register(Student)](https://user-images.githubusercontent.com/53752893/71513394-2bafe100-28c0-11ea-9563-2089186f019b.jpg)
###

**Comment by albseb511** [comment]
More information needed.
labels
who is going to work on this?

**Comment by 2211rohit** [comment]
I'm working on this

**Comment by 2211rohit** [comment]
PR raised https://github.com/masai-oss/quizera/pull/35. Kindly close the issue
