### ISSUE TITLE
Add Questions for Test UI - Teacher

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#10]
![Add Quiz(Teacher)(1)](https://user-images.githubusercontent.com/53752893/71532378-08fde680-2919-11ea-9a4e-4455fe8af0f6.png)

Route: /dashboard/create-test/add-question
File : components/AddQuestion.jsx
Description : Teacher's Dash board where teacher will  be redirected after entering the create test details and will be able add the questions as per the test details filled in the CREATE-TEST page.
Labels : Frontend , New , Question

**Comment by Madhu-kum** [comment]
I am working on this issue. kindly assign me.

**Comment by Madhu-kum** [comment]
PR raised for this issue kindly close the issue.
PR link : https://github.com/masai-oss/quizera/pull/38

**Comment by hrishabh8871** [comment]
PR raised kindly close this issue
PR link: https://github.com/masai-oss/quizera/pull/66
