### ISSUE TITLE
View Test Details UI-Teachers

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#11]
![Test Performance(Teacher)(2)](https://user-images.githubusercontent.com/53752893/71532485-917c8700-2919-11ea-863c-2efbccc1d261.png)

Route: /dashboard/view-details/:test-id
File: /components/ViewTestDetailsForTeachers.jsx
Description : Teacher will see all the details related with the test which is created by that particular teacher.
Labels : Front-end , New , Question

**Comment by ravigornal** [comment]
i am working on this

**Comment by ravigornal** [comment]
PR link: https://github.com/masai-oss/quizera/pull/133
