### ISSUE TITLE
View Details Of Students UI-Teachers 

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#12]
![Test Performance(Student)(1)](https://user-images.githubusercontent.com/53752893/71532598-1c5d8180-291a-11ea-9ad0-d2737d41c011.png)

Route: /dashboard/view-details/:test-id/:student-id
File: /components/TestDetailsForTeachers.jsx
Description : Teacher will see the result of the particular student with all the details of the student who have taken the test which is created by that particular teacher.
Labels : Front-end , New , Question

**Comment by Pavanpatil08** [comment]
I Will work on this issue.

**Comment by Pavanpatil08** [comment]
PR Raised:https://github.com/masai-oss/quizera/pull/136
