### ISSUE TITLE
Take Test UI - Student

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#13]
![Quiz Question(Student)](https://user-images.githubusercontent.com/53752893/71532867-8d516900-291b-11ea-840b-e84f33594656.png)
Route: /tests/:test-id
File: /components/AttemptQuestion.jsx
Description : Student will take the test which he have received from the teacher on the dashboard.
Labels : Front-end , New , Question

**Comment by amit036** [comment]
Assign me to this issue

**Comment by amit036** [comment]
PR Link - https://github.com/masai-oss/quizera/pull/34
