### ISSUE TITLE
Leaderboard UI -Teacher/Student/Admin

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#14]
![LeaderBoard(1)](https://user-images.githubusercontent.com/53752893/71532897-b8d45380-291b-11ea-9ad9-1bcdc5aa9fa9.png)

Route: /:test-id/leaderboard
File: /components/LeaderBoard.jsx
Description : Students will be able to see the Leader board if it is allowed by teacher. Teacher who has created the test will be able to see the leader board. Admin will be able to see all the leader board.
Labels : Front-end , New , Question

**Comment by rohitkumar202** [comment]
I want to work on this issue
