### ISSUE TITLE
About Us UI

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#15]
![About Us(1)](https://user-images.githubusercontent.com/53752893/71533016-69425780-291c-11ea-9204-de6b144e33ee.png)
 
Route: /aboutus
File: /components/AboutUs.jsx
Description : Description about the website
Labels : Front-end , New , Question

**Comment by 2211rohit** [comment]
I'm working on this

**Comment by 2211rohit** [comment]
Completed and PR raised.
Link: https://github.com/masai-oss/quizera/pull/31
