### ISSUE TITLE
BluePrint For Admin 

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#150]
It consists of all routes associated with admin.
    signup,add_batch,add_section,add_test_type,add_objective_type,delete_batch,delete_section,delete_test_type,delete_objective_type,all_batches,all_sections,all_test_types,all_objective_type,all_teachers,all_students_batchwise,add_student_section

labels:- Backend, new, feature

**Comment by amit036** [comment]
I am working on this issue
