### ISSUE TITLE
Contact Us UI

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#16]
![Contact Us(2)](https://user-images.githubusercontent.com/53752893/71533064-ad355c80-291c-11ea-8723-75c25e91eac1.png)

Route: /contact
File: /components/ContactUs.jsx
Description :Contact us for the website where anyone can contact us if any issue or suggestion and contact details will be provided
Labels : Front-end , New , Question

**Comment by 2211rohit** [comment]
I'm working on this

**Comment by 2211rohit** [comment]
This is completed and PR is raised https://github.com/masai-oss/quizera/pull/32
