### ISSUE TITLE
Api Docs for Student

### ISSUE THREAD

**Issue by hrishabh8871** [masai-oss/quizera#17]
This issue is regarding API docs creation for Student.
**Endpoints -**

1. - Register
2. - Login
3. - Add and Edit Profile
4. - Assessment by student
5. - Progress and Dashboard

**Lables -**

1. - Backend
2. - in_progress
3. - documentation
4. - assigned

**Comment by hrishabh8871** [comment]
Amit and Hrishabh wants to work on it.

**Comment by amit036** [comment]
I also want to work on this issue

**Comment by albseb511** [comment]
lables are wrong.
its not a feature, not new.
Fix that
