### ISSUE TITLE
Api Docs for Teacher

### ISSUE THREAD

**Issue by hrishabh8871** [masai-oss/quizera#18]
This issue is regarding API docs creation for Teacher.
**Endpoints -**

1. - Register
2. - Login
3. - Edit Profile
4. - Add Quiz
5. - Quiz settings
6. - Publish Quiz
7. - See Student Reports
8. - Check Manually for Subjective Quiz

**Lables -**

1. - Backend
2. - in_progress
3. - documentation
4. - assigned

**Comment by amit036** [comment]
I want to work on this issue

**Comment by hrishabh8871** [comment]
I want to work on this issue

**Comment by albseb511** [comment]
lables are wrong.
its not a feature, not new.
Fix that
