### ISSUE TITLE
Teacher Register UI

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#2]
![Register(Teacher)(1)](https://user-images.githubusercontent.com/53752893/71513690-6a926680-28c1-11ea-8c55-6f1149858335.png)

**Comment by albseb511** [comment]
More information needed.
labels
who is going to work on this?

**Comment by 2211rohit** [comment]
I'm working on this

**Comment by Madhu-kum** [comment]
This is no longer present and now only one common registration page is being used. Hence closing this issue.
