### ISSUE TITLE
NavBar UI

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#20]
![Screenshot_2019-12-28 React App](https://user-images.githubusercontent.com/53752893/71541577-22d31400-2981-11ea-907b-c5e50aef2c1d.png)

File: NavBarPublic.jsx
Description: Navigation bar for the website
Labels : Front-end, New, Question

**Comment by Madhu-kum** [comment]
I am working on this

**Comment by Madhu-kum** [comment]
Need to look into this.
Label: Bug

PR link : https://github.com/masai-oss/quizera/pull/79

**Comment by Madhu-kum** [comment]
Need to look into this.
Label: Bug

PR link : https://github.com/masai-oss/quizera/pull/83

**Comment by ravigornal** [comment]
i am working on this

**Comment by rohitkumar202** [comment]
assign me to this issue
