### ISSUE TITLE
API auth routes for Admin

### ISSUE THREAD

**Issue by hrishabh8871** [masai-oss/quizera#27]
This issue is regarding API routes creation for Admin.
**Endpoints -**
1. - Register
2. - Login

**Lables -**

1. -  Backend
2. -  in_progress
3. -  documentation
4. -  assigned

**Comment by hrishabh8871** [comment]
Please assign to me

**Comment by albseb511** [comment]
Why is this marked as documentation?

**Comment by hrishabh8871** [comment]
PR generated please close this issue
PR link: https://github.com/masai-oss/quizera/pull/74
