### ISSUE TITLE
API auth routes for Teacher 

### ISSUE THREAD

**Issue by hrishabh8871** [masai-oss/quizera#28]
This issue is regarding API routes creation for Teacher.
**Endpoints -**

1. - Register
2. - Login

**Lables -**

1. - Backend
2. - in_progress
3. - assigned

**Comment by hrishabh8871** [comment]
I want to work on it

**Comment by albseb511** [comment]
Why is this marked as documentation?

**Comment by hrishabh8871** [comment]
Please close this issue
PR link: https://github.com/masai-oss/quizera/pull/76
