### ISSUE TITLE
 API auth routes for Student 

### ISSUE THREAD

**Issue by hrishabh8871** [masai-oss/quizera#29]
This issue is regarding API routes creation for Student.
**Endpoints -**

1. - Register
2. - Login

**Lables -**

1. - Backend
2. - in_progress
3. - assigned

**Comment by hrishabh8871** [comment]
Please assign to me

**Comment by albseb511** [comment]
why is this marked as documentation?

**Comment by hrishabh8871** [comment]
Please close this issue
PR link: https://github.com/masai-oss/quizera/pull/75
