### ISSUE TITLE
Admin Registration UI

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#3]
![Register(Admin)](https://user-images.githubusercontent.com/53752893/71513780-d83e9280-28c1-11ea-8286-670987269d70.png)

Route: /registration
File: component/AdminRegister.jsx
Description : Admin will enter the required details for registration.
Labels : Frontend , New

**Comment by Madhu-kum** [comment]
Route: /admin
File: Component/AdminRegister

**Comment by albseb511** [comment]
Filename and path is wrong.
More information needed.
labels
who is going to work on this?

**Comment by 2211rohit** [comment]
I'm working on this

**Comment by 2211rohit** [comment]
This is completed and pull request is raised.

**Comment by 2211rohit** [comment]
Pull request raised and merged. https://github.com/masai-oss/quizera/pull/22
Kindly close the issue
