### ISSUE TITLE
Api Docs for admin

### ISSUE THREAD

**Issue by hrishabh8871** [masai-oss/quizera#4]
This issue is regarding API docs creation for Admin.
**Endpoints -** 
1.  Register
2.  Login
3.  Add and Delete Batch / Class
4.  Add and Delete Section
5.  Add Students to Sections
6.  Remove Students from Section
7.  Get All Details of Batches
8.  Get All Details of Sections
9.  Get All Students Details
10. Add and Delete quiz type (Subjective, Objective, etc)

**Lables -**

1. - Backend
2. - in_progress
3. - documentation
4. - assigned

**Comment by albseb511** [comment]
please describe what API docs you need to make? 
Please mention the details and who is going to work on this along with the labels applicable.

**Comment by hrishabh8871** [comment]
Amit & Hrishabh wants to work on this issue

**Comment by amit036** [comment]
Assign me to this issue

**Comment by amit036** [comment]
Kindly Close the issue as PR is approved.
PR Link: https://github.com/masai-oss/quizera/pull/23
