### ISSUE TITLE
Admin :-  Batch Wise Student List API

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#44]
Admin will get the lists of all registered students batch wise.

route: /admin/all_student_batchwise

Label: New, backend, api, question

**Comment by amit036** [comment]
assign me to this issue

**Comment by amit036** [comment]
Please Close this Issue 
I have Completed this API

**Comment by albseb511** [comment]
PR Link: https://github.com/masai-oss/quizera/pull/95
