### ISSUE TITLE
StudentDashBoardUI

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#5]
![Dashborad(Student)](https://user-images.githubusercontent.com/53752893/71526995-671dd000-28ff-11ea-9db1-5a7048d1b70e.png)

Route: /dashboard
File : components/StudentsDashBoard.jsx
Description : Student Dash board where student will be routed after login.
Labels : Frontend , New , Question

**Comment by 2211rohit** [comment]
I'm working on this!

**Comment by 2211rohit** [comment]
This is completed and PR request is raised https://github.com/masai-oss/quizera/pull/43
