### ISSUE TITLE
Create Models For Backend

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#65]
Table Creation:-
 1. Admin
 2. Student
 3. Teacher
 4.Batch
 5. Section
 6. Test Type
 7. Quiz Set
 8. Question Type
 9. Objective question
 10. Submission Objective
 
Labels:Backend, Question, New

**Comment by 2211rohit** [comment]
I'm working on this

**Comment by albseb511** [comment]
Whats the update on this?

**Comment by Madhu-kum** [comment]
Issue raised for the all the models separately hence closing this issue.
Reference link of all the issue raised.
https://github.com/masai-oss/quizera/issues/137
https://github.com/masai-oss/quizera/issues/138
https://github.com/masai-oss/quizera/issues/139
https://github.com/masai-oss/quizera/issues/140
https://github.com/masai-oss/quizera/issues/141
https://github.com/masai-oss/quizera/issues/142
https://github.com/masai-oss/quizera/issues/143
https://github.com/masai-oss/quizera/issues/144
https://github.com/masai-oss/quizera/issues/145
https://github.com/masai-oss/quizera/issues/146
https://github.com/masai-oss/quizera/issues/147
https://github.com/masai-oss/quizera/issues/148
https://github.com/masai-oss/quizera/issues/156
