### ISSUE TITLE
Admin DashBoard UI

### ISSUE THREAD

**Issue by Madhu-kum** [masai-oss/quizera#8]
![DashBoard(Admin)](https://user-images.githubusercontent.com/53752893/71530333-4f4e4800-290f-11ea-83ce-cb51f753ebbb.png)
Route: /dashboard
File : components/AdminDashBoard.jsx
Description : Admin Dash board where admin will be routed after login.
Labels : Frontend , New , Question

**Comment by hrishabh8871** [comment]
Please assign to me
